---
- name: UnInstall apache/httpd webserver
  hosts: loadbalancer 
  tasks:
  - name: Ensure httpd is stopped
    service:
      name: httpd
      state: stopped 
  - name: UnInstall httpd packages
    yum:
      name: httpd
      state: absent 
